# Language
language:
 - python
# Supported version
python:
 - 3.6
# Install dependecies
install:
 - pip install -r requirements.txt
# Database service
services:
 - postgresql
# Database setup
before_script:
 - psql -c 'create database test_recipe;' -U postgres
 - psql -c 'create database recipe;' -U postgres
# Test Script
script:
  -  nosetests --with-coverage --cover-tests --cover-erase --cover-package=api

# Coveralls reporting
after_success:
 - coveralls
